-- MySQL Script generated by MySQL Workbench
-- Fri Jun 10 17:22:09 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema proyecto_final_bbdd
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema proyecto_final_bbdd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `proyecto_final_bbdd` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `proyecto_final_bbdd` ;

-- -----------------------------------------------------
-- Table `proyecto_final_bbdd`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_final_bbdd`.`address` (
  `address_id` INT NOT NULL,
  `city` VARCHAR(100) NULL DEFAULT NULL,
  `country` VARCHAR(45) NOT NULL,
  `zip_code` INT NOT NULL,
  PRIMARY KEY (`address_id`),
  UNIQUE INDEX `address_id_UNIQUE` (`address_id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `proyecto_final_bbdd`.`client_account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_final_bbdd`.`client_account` (
  `user_account_id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `date_joined` DATETIME NOT NULL,
  `phone_no` VARCHAR(45) NULL DEFAULT NULL,
  `email_notifications_active` TINYINT NOT NULL DEFAULT '0',
  PRIMARY KEY (`user_account_id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 15712
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `proyecto_final_bbdd`.`company_profile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_final_bbdd`.`company_profile` (
  `company_id` INT NOT NULL,
  `company_name` VARCHAR(150) NULL DEFAULT NULL,
  `description` VARCHAR(45) NULL DEFAULT NULL,
  `company_size` ENUM('START UP', 'SMALL', 'MEDIUM', 'BIG') NULL DEFAULT NULL,
  `num_employees` INT NULL DEFAULT NULL,
  `creation_date` DATE NOT NULL,
  `company_website` VARCHAR(45) NULL DEFAULT NULL,
  `address_id` INT NOT NULL,
  `user_account_id` INT NOT NULL,
  PRIMARY KEY (`company_id`),
  INDEX `fk_COMPANY_PROFILE_ADDRESS1_idx` (`address_id` ASC) VISIBLE,
  INDEX `fk_COMPANY_PROFILE_CLIENT_ACCOUNT1_idx` (`user_account_id` ASC) VISIBLE,
  CONSTRAINT `fk_COMPANY_PROFILE_ADDRESS1`
    FOREIGN KEY (`address_id`)
    REFERENCES `proyecto_final_bbdd`.`address` (`address_id`),
  CONSTRAINT `fk_COMPANY_PROFILE_CLIENT_ACCOUNT1`
    FOREIGN KEY (`user_account_id`)
    REFERENCES `proyecto_final_bbdd`.`client_account` (`user_account_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `proyecto_final_bbdd`.`job_offer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_final_bbdd`.`job_offer` (
  `job_offer_id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(200) NULL DEFAULT NULL,
  `company` VARCHAR(100) NOT NULL,
  `description` VARCHAR(1000) NULL DEFAULT NULL,
  `status` TINYINT NOT NULL,
  `location` VARCHAR(100) NULL DEFAULT NULL,
  `modality` VARCHAR(100) NULL DEFAULT NULL,
  `release_date` DATE NOT NULL,
  `agreement` VARCHAR(100) NULL DEFAULT NULL,
  `work_time` VARCHAR(100) NULL DEFAULT NULL,
  `salary` INT NULL DEFAULT NULL,
  `education` VARCHAR(100) NULL DEFAULT NULL,
  `category` VARCHAR(100) NULL DEFAULT NULL,
  `company_id` INT NOT NULL,
  PRIMARY KEY (`job_offer_id`),
  UNIQUE INDEX `job_offer_id_UNIQUE` (`job_offer_id` ASC) VISIBLE,
  INDEX `fk_JOB_OFFER_COMPANY_PROFILE1_idx` (`company_id` ASC) VISIBLE,
  CONSTRAINT `fk_JOB_OFFER_COMPANY_PROFILE1`
    FOREIGN KEY (`company_id`)
    REFERENCES `proyecto_final_bbdd`.`company_profile` (`company_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 41180
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `proyecto_final_bbdd`.`user_profile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_final_bbdd`.`user_profile` (
  `profile_id` INT NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NULL DEFAULT NULL,
  `image` BLOB NULL DEFAULT NULL,
  `profile_type` ENUM('WORKING', 'SEARCHING', 'UNKNOWN') NOT NULL DEFAULT 'UNKNOWN',
  `gender` ENUM('MAN', 'WOMAN', 'OTHER') NOT NULL DEFAULT 'OTHER',
  `address_id` INT NULL DEFAULT NULL,
  `user_account_id` INT NOT NULL,
  PRIMARY KEY (`profile_id`),
  INDEX `fk_USER_PROFILE_ADDRESS1_idx` (`address_id` ASC) VISIBLE,
  INDEX `fk_USER_PROFILE_CLIENT_ACCOUNT1_idx` (`user_account_id` ASC) VISIBLE,
  CONSTRAINT `fk_USER_PROFILE_ADDRESS1`
    FOREIGN KEY (`address_id`)
    REFERENCES `proyecto_final_bbdd`.`address` (`address_id`),
  CONSTRAINT `fk_USER_PROFILE_CLIENT_ACCOUNT1`
    FOREIGN KEY (`user_account_id`)
    REFERENCES `proyecto_final_bbdd`.`client_account` (`user_account_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `proyecto_final_bbdd`.`application`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_final_bbdd`.`application` (
  `job_offer_id` INT NOT NULL,
  `profile_id` INT NOT NULL,
  `state` ENUM('PENDING', 'REJECTED', 'ACCEPTED') NOT NULL DEFAULT 'PENDING',
  `aplication_date` DATE NOT NULL,
  PRIMARY KEY (`job_offer_id`, `profile_id`),
  INDEX `fk_JOB_OFFER_has_USER_PROFILE_USER_PROFILE1_idx` (`profile_id` ASC) VISIBLE,
  INDEX `fk_JOB_OFFER_has_USER_PROFILE_JOB_OFFER1_idx` (`job_offer_id` ASC) VISIBLE,
  CONSTRAINT `fk_JOB_OFFER_has_USER_PROFILE_JOB_OFFER1`
    FOREIGN KEY (`job_offer_id`)
    REFERENCES `proyecto_final_bbdd`.`job_offer` (`job_offer_id`),
  CONSTRAINT `fk_JOB_OFFER_has_USER_PROFILE_USER_PROFILE1`
    FOREIGN KEY (`profile_id`)
    REFERENCES `proyecto_final_bbdd`.`user_profile` (`profile_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `proyecto_final_bbdd`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_final_bbdd`.`category` (
  `category_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`category_name`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `proyecto_final_bbdd`.`certificates`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_final_bbdd`.`certificates` (
  `certificate_id` INT NOT NULL,
  `certificate_url` VARCHAR(45) NULL DEFAULT NULL,
  `expedition_company` VARCHAR(45) NULL DEFAULT NULL,
  `expedition_date` DATE NULL DEFAULT NULL,
  `profile_id` INT NOT NULL,
  PRIMARY KEY (`certificate_id`),
  INDEX `fk_CERTIFICATES_USER_PROFILE1_idx` (`profile_id` ASC) VISIBLE,
  CONSTRAINT `fk_CERTIFICATES_USER_PROFILE1`
    FOREIGN KEY (`profile_id`)
    REFERENCES `proyecto_final_bbdd`.`user_profile` (`profile_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `proyecto_final_bbdd`.`client_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_final_bbdd`.`client_log` (
  `user_account_id` INT NOT NULL,
  `last_login_date` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`user_account_id`),
  CONSTRAINT `fk_CLIENT_LOG_CLIENT_ACCOUNT`
    FOREIGN KEY (`user_account_id`)
    REFERENCES `proyecto_final_bbdd`.`client_account` (`user_account_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `proyecto_final_bbdd`.`company_social_media`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_final_bbdd`.`company_social_media` (
  `cs_media_id` INT NOT NULL,
  `type` ENUM('FB', 'INSTAGRAM', 'TWITTER') NOT NULL,
  `url` BLOB NULL DEFAULT NULL,
  `COMPANY_PROFILE_company_id` INT NOT NULL,
  PRIMARY KEY (`cs_media_id`),
  INDEX `fk_COMPANY_SOCIAL_MEDIA_COMPANY_PROFILE1_idx` (`COMPANY_PROFILE_company_id` ASC) VISIBLE,
  CONSTRAINT `fk_COMPANY_SOCIAL_MEDIA_COMPANY_PROFILE1`
    FOREIGN KEY (`COMPANY_PROFILE_company_id`)
    REFERENCES `proyecto_final_bbdd`.`company_profile` (`company_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `proyecto_final_bbdd`.`cv`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_final_bbdd`.`cv` (
  `cv_id` INT NOT NULL,
  `profile_id` INT NOT NULL,
  `cv_url` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`cv_id`, `profile_id`),
  INDEX `fk_CV_USER_PROFILE1_idx` (`profile_id` ASC) VISIBLE,
  CONSTRAINT `fk_CV_USER_PROFILE1`
    FOREIGN KEY (`profile_id`)
    REFERENCES `proyecto_final_bbdd`.`user_profile` (`profile_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `proyecto_final_bbdd`.`education`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_final_bbdd`.`education` (
  `education_id` INT NOT NULL,
  `education_type` ENUM('FURTHER EDU', 'HIGH SCHOOL', 'DEGREE', 'POST DEGREE', 'MASTER', 'OTHER') NOT NULL DEFAULT 'OTHER',
  `title` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NULL DEFAULT NULL,
  `date_start` DATE NOT NULL,
  `date_ending` DATE NULL DEFAULT NULL,
  `institution_name` VARCHAR(45) NOT NULL,
  `EDUCATIONcol` VARCHAR(45) NULL DEFAULT NULL,
  `profile_id` INT NOT NULL,
  `certificate_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`education_id`),
  INDEX `fk_EDUCATION_USER_PROFILE1_idx` (`profile_id` ASC) VISIBLE,
  INDEX `fk_EDUCATION_CERTIFICATES1_idx` (`certificate_id` ASC) VISIBLE,
  CONSTRAINT `fk_EDUCATION_CERTIFICATES1`
    FOREIGN KEY (`certificate_id`)
    REFERENCES `proyecto_final_bbdd`.`certificates` (`certificate_id`),
  CONSTRAINT `fk_EDUCATION_USER_PROFILE1`
    FOREIGN KEY (`profile_id`)
    REFERENCES `proyecto_final_bbdd`.`user_profile` (`profile_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `proyecto_final_bbdd`.`experience`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_final_bbdd`.`experience` (
  `experience_id` INT NOT NULL,
  `experience_type` ENUM('RELATED', 'NON-RELATED') NOT NULL DEFAULT 'NON-RELATED',
  `title` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NULL DEFAULT NULL,
  `date_start` DATE NOT NULL,
  `date_ending` DATE NULL DEFAULT NULL,
  `company_name` VARCHAR(45) NOT NULL,
  `profile_id` INT NOT NULL,
  `certificate_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`experience_id`),
  INDEX `fk_EXPERIENCE_USER_PROFILE1_idx` (`profile_id` ASC) VISIBLE,
  INDEX `fk_EXPERIENCE_CERTIFICATES1_idx` (`certificate_id` ASC) VISIBLE,
  CONSTRAINT `fk_EXPERIENCE_CERTIFICATES1`
    FOREIGN KEY (`certificate_id`)
    REFERENCES `proyecto_final_bbdd`.`certificates` (`certificate_id`),
  CONSTRAINT `fk_EXPERIENCE_USER_PROFILE1`
    FOREIGN KEY (`profile_id`)
    REFERENCES `proyecto_final_bbdd`.`user_profile` (`profile_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `proyecto_final_bbdd`.`interests`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_final_bbdd`.`interests` (
  `interest_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`interest_name`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `proyecto_final_bbdd`.`interests_has_user_profile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_final_bbdd`.`interests_has_user_profile` (
  `interest_name` VARCHAR(45) NOT NULL,
  `profile_id` INT NOT NULL,
  PRIMARY KEY (`interest_name`, `profile_id`),
  INDEX `fk_INTERESTS_has_USER_PROFILE_USER_PROFILE1_idx` (`profile_id` ASC) VISIBLE,
  INDEX `fk_INTERESTS_has_USER_PROFILE_INTERESTS1_idx` (`interest_name` ASC) VISIBLE,
  CONSTRAINT `fk_INTERESTS_has_USER_PROFILE_INTERESTS1`
    FOREIGN KEY (`interest_name`)
    REFERENCES `proyecto_final_bbdd`.`interests` (`interest_name`),
  CONSTRAINT `fk_INTERESTS_has_USER_PROFILE_USER_PROFILE1`
    FOREIGN KEY (`profile_id`)
    REFERENCES `proyecto_final_bbdd`.`user_profile` (`profile_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `proyecto_final_bbdd`.`job_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_final_bbdd`.`job_category` (
  `category_name` VARCHAR(45) NOT NULL,
  `job_offer_id` INT NOT NULL,
  PRIMARY KEY (`category_name`, `job_offer_id`),
  INDEX `fk_CATEGORY_has_JOB_OFFER_JOB_OFFER1_idx` (`job_offer_id` ASC) VISIBLE,
  INDEX `fk_CATEGORY_has_JOB_OFFER_CATEGORY1_idx` (`category_name` ASC) VISIBLE,
  CONSTRAINT `fk_CATEGORY_has_JOB_OFFER_CATEGORY1`
    FOREIGN KEY (`category_name`)
    REFERENCES `proyecto_final_bbdd`.`category` (`category_name`),
  CONSTRAINT `fk_CATEGORY_has_JOB_OFFER_JOB_OFFER1`
    FOREIGN KEY (`job_offer_id`)
    REFERENCES `proyecto_final_bbdd`.`job_offer` (`job_offer_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `proyecto_final_bbdd`.`tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_final_bbdd`.`tags` (
  `tag_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`tag_name`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `proyecto_final_bbdd`.`job_tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_final_bbdd`.`job_tag` (
  `tag_name` VARCHAR(45) NOT NULL,
  `job_offer_id` INT NOT NULL,
  PRIMARY KEY (`tag_name`, `job_offer_id`),
  INDEX `fk_TAGS_has_JOB_OFFER_JOB_OFFER1_idx` (`job_offer_id` ASC) VISIBLE,
  INDEX `fk_TAGS_has_JOB_OFFER_TAGS1_idx` (`tag_name` ASC) VISIBLE,
  CONSTRAINT `fk_TAGS_has_JOB_OFFER_JOB_OFFER1`
    FOREIGN KEY (`job_offer_id`)
    REFERENCES `proyecto_final_bbdd`.`job_offer` (`job_offer_id`),
  CONSTRAINT `fk_TAGS_has_JOB_OFFER_TAGS1`
    FOREIGN KEY (`tag_name`)
    REFERENCES `proyecto_final_bbdd`.`tags` (`tag_name`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `proyecto_final_bbdd`.`languages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_final_bbdd`.`languages` (
  `language_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`language_name`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `proyecto_final_bbdd`.`languages_has_user_profile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_final_bbdd`.`languages_has_user_profile` (
  `language_name` VARCHAR(45) NOT NULL,
  `profile_id` INT NOT NULL,
  `Level` ENUM('BASIC', 'INTERMEDIATE', 'ADVANCED', 'NATIVE', 'UNKNOWN') NOT NULL DEFAULT 'UNKNOWN',
  `certificate_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`language_name`, `profile_id`),
  INDEX `fk_LANGUAGES_has_USER_PROFILE_USER_PROFILE1_idx` (`profile_id` ASC) VISIBLE,
  INDEX `fk_LANGUAGES_has_USER_PROFILE_LANGUAGES1_idx` (`language_name` ASC) VISIBLE,
  INDEX `fk_LANGUAGES_has_USER_PROFILE_CERTIFICATES1_idx` (`certificate_id` ASC) VISIBLE,
  CONSTRAINT `fk_LANGUAGES_has_USER_PROFILE_CERTIFICATES1`
    FOREIGN KEY (`certificate_id`)
    REFERENCES `proyecto_final_bbdd`.`certificates` (`certificate_id`),
  CONSTRAINT `fk_LANGUAGES_has_USER_PROFILE_LANGUAGES1`
    FOREIGN KEY (`language_name`)
    REFERENCES `proyecto_final_bbdd`.`languages` (`language_name`),
  CONSTRAINT `fk_LANGUAGES_has_USER_PROFILE_USER_PROFILE1`
    FOREIGN KEY (`profile_id`)
    REFERENCES `proyecto_final_bbdd`.`user_profile` (`profile_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
