-- MySQL Script generated by MySQL Workbench
-- dom 05 jun 2022 11:38:14
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Proyecto_BBDD
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Proyecto_BBDD
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Proyecto_BBDD` DEFAULT CHARACTER SET utf8 ;
USE `Proyecto_BBDD` ;

-- -----------------------------------------------------
-- Table `Proyecto_BBDD`.`CLIENT_ACCOUNT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto_BBDD`.`CLIENT_ACCOUNT` (
  `user_account_id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `date_joined` DATETIME NOT NULL,
  `phone_no` VARCHAR(45) NULL,
  `email_notifications_active` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`user_account_id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Proyecto_BBDD`.`CLIENT_LOG`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto_BBDD`.`CLIENT_LOG` (
  `user_account_id` INT NOT NULL,
  `last_login_date` TIMESTAMP NULL,
  PRIMARY KEY (`user_account_id`),
  CONSTRAINT `fk_CLIENT_LOG_CLIENT_ACCOUNT`
    FOREIGN KEY (`user_account_id`)
    REFERENCES `Proyecto_BBDD`.`CLIENT_ACCOUNT` (`user_account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Proyecto_BBDD`.`ADDRESS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto_BBDD`.`ADDRESS` (
  `address_id` INT NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  `zip_code` INT NOT NULL,
  PRIMARY KEY (`address_id`),
  UNIQUE INDEX `address_id_UNIQUE` (`address_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Proyecto_BBDD`.`USER_PROFILE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto_BBDD`.`USER_PROFILE` (
  `profile_id` INT NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NULL,
  `image` BLOB NULL,
  `profile_type` ENUM('WORKING', 'SEARCHING', 'UNKNOWN') NOT NULL DEFAULT 'UNKNOWN',
  `gender` ENUM('MAN', 'WOMAN', 'OTHER') NOT NULL DEFAULT 'OTHER',
  `address_id` INT NULL,
  `user_account_id` INT NOT NULL,
  PRIMARY KEY (`profile_id`),
  INDEX `fk_USER_PROFILE_ADDRESS1_idx` (`address_id` ASC) VISIBLE,
  INDEX `fk_USER_PROFILE_CLIENT_ACCOUNT1_idx` (`user_account_id` ASC) VISIBLE,
  CONSTRAINT `fk_USER_PROFILE_ADDRESS1`
    FOREIGN KEY (`address_id`)
    REFERENCES `Proyecto_BBDD`.`ADDRESS` (`address_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_USER_PROFILE_CLIENT_ACCOUNT1`
    FOREIGN KEY (`user_account_id`)
    REFERENCES `Proyecto_BBDD`.`CLIENT_ACCOUNT` (`user_account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Proyecto_BBDD`.`CERTIFICATES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto_BBDD`.`CERTIFICATES` (
  `certificate_id` INT NOT NULL,
  `certificate_url` VARCHAR(45) NULL,
  `expedition_company` VARCHAR(45) NULL,
  `expedition_date` DATE NULL,
  `profile_id` INT NOT NULL,
  PRIMARY KEY (`certificate_id`),
  INDEX `fk_CERTIFICATES_USER_PROFILE1_idx` (`profile_id` ASC) VISIBLE,
  CONSTRAINT `fk_CERTIFICATES_USER_PROFILE1`
    FOREIGN KEY (`profile_id`)
    REFERENCES `Proyecto_BBDD`.`USER_PROFILE` (`profile_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Proyecto_BBDD`.`CV`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto_BBDD`.`CV` (
  `cv_id` INT NOT NULL,
  `profile_id` INT NOT NULL,
  `cv_url` VARCHAR(45) NULL,
  PRIMARY KEY (`cv_id`, `profile_id`),
  INDEX `fk_CV_USER_PROFILE1_idx` (`profile_id` ASC) VISIBLE,
  CONSTRAINT `fk_CV_USER_PROFILE1`
    FOREIGN KEY (`profile_id`)
    REFERENCES `Proyecto_BBDD`.`USER_PROFILE` (`profile_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Proyecto_BBDD`.`EDUCATION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto_BBDD`.`EDUCATION` (
  `education_id` INT NOT NULL,
  `education_type` ENUM('FURTHER EDU', 'HIGH SCHOOL', 'DEGREE', 'POST DEGREE', 'MASTER', 'OTHER') NOT NULL DEFAULT 'OTHER',
  `title` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NULL,
  `date_start` DATE NOT NULL,
  `date_ending` DATE NULL,
  `institution_name` VARCHAR(45) NOT NULL,
  `EDUCATIONcol` VARCHAR(45) NULL,
  `profile_id` INT NOT NULL,
  `certificate_id` INT NULL,
  PRIMARY KEY (`education_id`),
  INDEX `fk_EDUCATION_USER_PROFILE1_idx` (`profile_id` ASC) VISIBLE,
  INDEX `fk_EDUCATION_CERTIFICATES1_idx` (`certificate_id` ASC) VISIBLE,
  CONSTRAINT `fk_EDUCATION_USER_PROFILE1`
    FOREIGN KEY (`profile_id`)
    REFERENCES `Proyecto_BBDD`.`USER_PROFILE` (`profile_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EDUCATION_CERTIFICATES1`
    FOREIGN KEY (`certificate_id`)
    REFERENCES `Proyecto_BBDD`.`CERTIFICATES` (`certificate_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Proyecto_BBDD`.`EXPERIENCE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto_BBDD`.`EXPERIENCE` (
  `experience_id` INT NOT NULL,
  `experience_type` ENUM('RELATED', 'NON-RELATED') NOT NULL DEFAULT 'NON-RELATED',
  `title` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NULL,
  `date_start` DATE NOT NULL,
  `date_ending` DATE NULL,
  `company_name` VARCHAR(45) NOT NULL,
  `profile_id` INT NOT NULL,
  `certificate_id` INT NULL,
  PRIMARY KEY (`experience_id`),
  INDEX `fk_EXPERIENCE_USER_PROFILE1_idx` (`profile_id` ASC) VISIBLE,
  INDEX `fk_EXPERIENCE_CERTIFICATES1_idx` (`certificate_id` ASC) VISIBLE,
  CONSTRAINT `fk_EXPERIENCE_USER_PROFILE1`
    FOREIGN KEY (`profile_id`)
    REFERENCES `Proyecto_BBDD`.`USER_PROFILE` (`profile_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EXPERIENCE_CERTIFICATES1`
    FOREIGN KEY (`certificate_id`)
    REFERENCES `Proyecto_BBDD`.`CERTIFICATES` (`certificate_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Proyecto_BBDD`.`LANGUAGES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto_BBDD`.`LANGUAGES` (
  `language_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`language_name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Proyecto_BBDD`.`LANGUAGES_has_USER_PROFILE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto_BBDD`.`LANGUAGES_has_USER_PROFILE` (
  `language_name` VARCHAR(45) NOT NULL,
  `profile_id` INT NOT NULL,
  `Level` ENUM('BASIC', 'INTERMEDIATE', 'ADVANCED', 'NATIVE', 'UNKNOWN') NOT NULL DEFAULT 'UNKNOWN',
  `certificate_id` INT NULL,
  PRIMARY KEY (`language_name`, `profile_id`),
  INDEX `fk_LANGUAGES_has_USER_PROFILE_USER_PROFILE1_idx` (`profile_id` ASC) VISIBLE,
  INDEX `fk_LANGUAGES_has_USER_PROFILE_LANGUAGES1_idx` (`language_name` ASC) VISIBLE,
  INDEX `fk_LANGUAGES_has_USER_PROFILE_CERTIFICATES1_idx` (`certificate_id` ASC) VISIBLE,
  CONSTRAINT `fk_LANGUAGES_has_USER_PROFILE_LANGUAGES1`
    FOREIGN KEY (`language_name`)
    REFERENCES `Proyecto_BBDD`.`LANGUAGES` (`language_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_LANGUAGES_has_USER_PROFILE_USER_PROFILE1`
    FOREIGN KEY (`profile_id`)
    REFERENCES `Proyecto_BBDD`.`USER_PROFILE` (`profile_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_LANGUAGES_has_USER_PROFILE_CERTIFICATES1`
    FOREIGN KEY (`certificate_id`)
    REFERENCES `Proyecto_BBDD`.`CERTIFICATES` (`certificate_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Proyecto_BBDD`.`INTERESTS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto_BBDD`.`INTERESTS` (
  `interest_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`interest_name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Proyecto_BBDD`.`INTERESTS_has_USER_PROFILE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto_BBDD`.`INTERESTS_has_USER_PROFILE` (
  `interest_name` VARCHAR(45) NOT NULL,
  `profile_id` INT NOT NULL,
  PRIMARY KEY (`interest_name`, `profile_id`),
  INDEX `fk_INTERESTS_has_USER_PROFILE_USER_PROFILE1_idx` (`profile_id` ASC) VISIBLE,
  INDEX `fk_INTERESTS_has_USER_PROFILE_INTERESTS1_idx` (`interest_name` ASC) VISIBLE,
  CONSTRAINT `fk_INTERESTS_has_USER_PROFILE_INTERESTS1`
    FOREIGN KEY (`interest_name`)
    REFERENCES `Proyecto_BBDD`.`INTERESTS` (`interest_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_INTERESTS_has_USER_PROFILE_USER_PROFILE1`
    FOREIGN KEY (`profile_id`)
    REFERENCES `Proyecto_BBDD`.`USER_PROFILE` (`profile_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Proyecto_BBDD`.`COMPANY_PROFILE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto_BBDD`.`COMPANY_PROFILE` (
  `company_id` INT NOT NULL,
  `company_name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NULL,
  `company_size` ENUM('START UP', 'SMALL', 'MEDIUM', 'BIG') NULL,
  `num_employees` INT NULL,
  `creation_date` DATE NOT NULL,
  `company_website` VARCHAR(45) NULL,
  `address_id` INT NOT NULL,
  `user_account_id` INT NOT NULL,
  PRIMARY KEY (`company_id`),
  INDEX `fk_COMPANY_PROFILE_ADDRESS1_idx` (`address_id` ASC) VISIBLE,
  INDEX `fk_COMPANY_PROFILE_CLIENT_ACCOUNT1_idx` (`user_account_id` ASC) VISIBLE,
  CONSTRAINT `fk_COMPANY_PROFILE_ADDRESS1`
    FOREIGN KEY (`address_id`)
    REFERENCES `Proyecto_BBDD`.`ADDRESS` (`address_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_COMPANY_PROFILE_CLIENT_ACCOUNT1`
    FOREIGN KEY (`user_account_id`)
    REFERENCES `Proyecto_BBDD`.`CLIENT_ACCOUNT` (`user_account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Proyecto_BBDD`.`COMPANY_SOCIAL_MEDIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto_BBDD`.`COMPANY_SOCIAL_MEDIA` (
  `cs_media_id` INT NOT NULL,
  `type` ENUM('FB', 'INSTAGRAM', 'TWITTER') NOT NULL,
  `url` BLOB NULL,
  `COMPANY_PROFILE_company_id` INT NOT NULL,
  PRIMARY KEY (`cs_media_id`),
  INDEX `fk_COMPANY_SOCIAL_MEDIA_COMPANY_PROFILE1_idx` (`COMPANY_PROFILE_company_id` ASC) VISIBLE,
  CONSTRAINT `fk_COMPANY_SOCIAL_MEDIA_COMPANY_PROFILE1`
    FOREIGN KEY (`COMPANY_PROFILE_company_id`)
    REFERENCES `Proyecto_BBDD`.`COMPANY_PROFILE` (`company_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Proyecto_BBDD`.`JOB_OFFER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto_BBDD`.`JOB_OFFER` (
  `job_offer_id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `description` VARCHAR(200) NULL,
  `status` TINYINT NOT NULL,
  `location` VARCHAR(45) NOT NULL,
  `modality` VARCHAR(45) NULL,
  `release_date` DATE NOT NULL,
  `agreement` VARCHAR(45) NOT NULL,
  `work_time` VARCHAR(45) NOT NULL,
  `salary` INT NULL,
  `education` VARCHAR(45) NOT NULL,
  `category` VARCHAR(45) NOT NULL,
  `company_id` INT NOT NULL,
  PRIMARY KEY (`job_offer_id`),
  INDEX `fk_JOB_OFFER_COMPANY_PROFILE1_idx` (`company_id` ASC) VISIBLE,
  UNIQUE INDEX `job_offer_id_UNIQUE` (`job_offer_id` ASC) VISIBLE,
  CONSTRAINT `fk_JOB_OFFER_COMPANY_PROFILE1`
    FOREIGN KEY (`company_id`)
    REFERENCES `Proyecto_BBDD`.`COMPANY_PROFILE` (`company_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Proyecto_BBDD`.`APPLICATION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto_BBDD`.`APPLICATION` (
  `job_offer_id` INT NOT NULL,
  `profile_id` INT NOT NULL,
  `state` ENUM('PENDING', 'REJECTED', 'ACCEPTED') NOT NULL DEFAULT 'PENDING',
  `aplication_date` DATE NOT NULL,
  PRIMARY KEY (`job_offer_id`, `profile_id`),
  INDEX `fk_JOB_OFFER_has_USER_PROFILE_USER_PROFILE1_idx` (`profile_id` ASC) VISIBLE,
  INDEX `fk_JOB_OFFER_has_USER_PROFILE_JOB_OFFER1_idx` (`job_offer_id` ASC) VISIBLE,
  CONSTRAINT `fk_JOB_OFFER_has_USER_PROFILE_JOB_OFFER1`
    FOREIGN KEY (`job_offer_id`)
    REFERENCES `Proyecto_BBDD`.`JOB_OFFER` (`job_offer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_JOB_OFFER_has_USER_PROFILE_USER_PROFILE1`
    FOREIGN KEY (`profile_id`)
    REFERENCES `Proyecto_BBDD`.`USER_PROFILE` (`profile_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Proyecto_BBDD`.`TAGS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto_BBDD`.`TAGS` (
  `tag_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`tag_name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Proyecto_BBDD`.`CATEGORY`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto_BBDD`.`CATEGORY` (
  `category_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`category_name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Proyecto_BBDD`.`JOB_TAG`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto_BBDD`.`JOB_TAG` (
  `tag_name` VARCHAR(45) NOT NULL,
  `job_offer_id` INT NOT NULL,
  PRIMARY KEY (`tag_name`, `job_offer_id`),
  INDEX `fk_TAGS_has_JOB_OFFER_JOB_OFFER1_idx` (`job_offer_id` ASC) VISIBLE,
  INDEX `fk_TAGS_has_JOB_OFFER_TAGS1_idx` (`tag_name` ASC) VISIBLE,
  CONSTRAINT `fk_TAGS_has_JOB_OFFER_TAGS1`
    FOREIGN KEY (`tag_name`)
    REFERENCES `Proyecto_BBDD`.`TAGS` (`tag_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TAGS_has_JOB_OFFER_JOB_OFFER1`
    FOREIGN KEY (`job_offer_id`)
    REFERENCES `Proyecto_BBDD`.`JOB_OFFER` (`job_offer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Proyecto_BBDD`.`JOB_CATEGORY`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto_BBDD`.`JOB_CATEGORY` (
  `category_name` VARCHAR(45) NOT NULL,
  `job_offer_id` INT NOT NULL,
  PRIMARY KEY (`category_name`, `job_offer_id`),
  INDEX `fk_CATEGORY_has_JOB_OFFER_JOB_OFFER1_idx` (`job_offer_id` ASC) VISIBLE,
  INDEX `fk_CATEGORY_has_JOB_OFFER_CATEGORY1_idx` (`category_name` ASC) VISIBLE,
  CONSTRAINT `fk_CATEGORY_has_JOB_OFFER_CATEGORY1`
    FOREIGN KEY (`category_name`)
    REFERENCES `Proyecto_BBDD`.`CATEGORY` (`category_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CATEGORY_has_JOB_OFFER_JOB_OFFER1`
    FOREIGN KEY (`job_offer_id`)
    REFERENCES `Proyecto_BBDD`.`JOB_OFFER` (`job_offer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
